version: '3'

services:
    backend:
        container_name: backend
        build: ./backend
        ports:
            - "5000:5000"
        networks:
            - transcendence_network
        restart: unless-stopped

    frontend:
        container_name: frontend
        build: ./frontend
        ports:
            - "3000:3000"
        networks:
            - transcendence_network
        restart: unless-stopped

networks:
    transcendence_network:
        driver: bridge
