version: '3'

services:
    backend:
        container_name: backend
        build: ./backend
        env_file:
            - .env
        ports:
            - "${BACKEND_PORT}:${BACKEND_PORT}"
        networks:
            - transcendence_network
        restart: unless-stopped

    frontend:
        container_name: frontend
        build: ./frontend
        env_file:
            - .env
        ports:
            - "${FRONTEND_PORT}:${FRONTEND_PORT}"
        networks:
            - transcendence_network
        restart: unless-stopped

networks:
    transcendence_network:
        driver: bridge
