version: '3'

services:
    db:
        image: postgres:14
        container_name: db
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        env_file:
            - ./backend/.env
        command: postgres -c listen_addresses=*
        networks:
            - transcendence_network

    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        env_file:
            - ./backend/.env
        ports:
            - "5001:5001"
        depends_on:
            - db
        networks:
            - transcendence_network
        restart: unless-stopped

    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        env_file:
            - ./frontend/.env
        ports:
            - "3000:3000"
        depends_on:
            - db
        networks:
            - transcendence_network
        restart: unless-stopped

    # prisma-studio:
    #   build:
    #     context: ./
    #     dockerfile: ./docker/prisma-studio/dockerfile
    #   container_name: prisma-studio
    #   depends_on:
    #     - backend
    #   environment:
    #     DATABASE_URL: "postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@dev-db:${DATABASE_PORT}/${DATABASE_NAME}?schema=public"
    #   volumes:
    #     - ./server:/server
    #   ports:
    #     - 5555:5555
    #   networks:
    #     - transcendence_network
    #   restart: always

volumes:
    pgdata:
        name: pgdata

networks:
    transcendence_network:
        driver: bridge
