version: '3'

services:
    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "5001:5001"
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - transcendence_network
        restart: unless-stopped

    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - db
        networks:
            - transcendence_network
        restart: unless-stopped
    
    db:
        image: postgres:14
        container_name: db
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        env_file:
            - .env
        networks:
            - transcendence_network

volumes:
    pgdata:
        name: pgdata

networks:
    transcendence_network:
        driver: bridge
